import { describe, it, expect } from 'vitest'
import * as enums from '../src/enums/index.js'

describe('All Pyrogram Enums in Nectogram', () => {
  it('should export all 44 high-level enums correctly', () => {
    expect(enums.BlockList.MAIN).toBe('main')
    expect(enums.BusinessSchedule.ALWAYS).toBe('always')
    expect(enums.ButtonStyle.PRIMARY).toBe('primary')
    expect(enums.ChatAction.TYPING).toBe('typing')
    expect(enums.ChatAction.CANCEL).toBe('cancel')
    expect(enums.ChatEventAction.TITLE_CHANGED).toBe('title_changed')
    expect(enums.ChatJoinRequestQueryResult.APPROVE).toBe('approve')
    expect(enums.ChatJoinType.BY_LINK).toBe('by_link')
    expect(enums.ChatMemberStatus.OWNER).toBe('owner')
    expect(enums.ChatMemberStatus.ADMINISTRATOR).toBe('administrator')
    expect(enums.ChatMembersFilter.ADMINISTRATORS).toBe('administrators')
    expect(enums.ChatPhotoStickerType.CUSTOM_EMOJI).toBe('custom_emoji')
    expect(enums.ChatType.PRIVATE).toBe('private')
    expect(enums.ChatType.SUPERGROUP).toBe('supergroup')
    expect(enums.ClientPlatform.ANDROID).toBe('android')
    expect(enums.FolderColor.RED).toBe('red')
    expect(enums.GiftAttributeType.MODEL).toBe('model')
    expect(enums.GiftForResaleOrder.PRICE).toBe('price')
    expect(enums.GiftPurchaseOfferState.PENDING).toBe('pending')
    expect(enums.GiftType.REGULAR).toBe('regular')
    expect(enums.MaskPointType.FOREHEAD).toBe('forehead')
    expect(enums.MediaAreaType.LOCATION).toBe('location')
    expect(enums.MessageEntityType.BOLD).toBe('bold')
    expect(enums.MessageEntityType.CUSTOM_EMOJI).toBe('custom_emoji')
    expect(enums.MessageMediaType.PHOTO).toBe('photo')
    expect(enums.MessageOriginType.USER).toBe('user')
    expect(enums.MessageServiceType.NEW_CHAT_MEMBERS).toBe('new_chat_members')
    expect(enums.MessagesFilter.PHOTO).toBe('photo')
    expect(enums.NextCodeType.SMS).toBe('sms')
    expect(enums.PaidReactionPrivacy.DEFAULT).toBe('default')
    expect(enums.ParseMode.MARKDOWN).toBe('markdown')
    expect(enums.PaymentFormType.REGULAR).toBe('regular')
    expect(enums.PhoneCallDiscardReason.MISSED).toBe('missed')
    expect(enums.PhoneNumberCodeType.AUTHENTICATION).toBe('authentication')
    expect(enums.PollType.QUIZ).toBe('quiz')
    expect(enums.PrivacyKey.PHONE_NUMBER).toBe('phone_number')
    expect(enums.PrivacyRuleType.ALLOW_ALL).toBe('allow_all')
    expect(enums.ProfileTab.MEDIA).toBe('media')
    expect(enums.ProxyScheme.SOCKS5).toBe('socks5')
    expect(enums.SentCodeType.APP).toBe('app')
    expect(enums.StickerType.REGULAR).toBe('regular')
    expect(enums.StoriesPrivacyRules.PUBLIC).toBe('public')
    expect(enums.SuggestedPostRefundReason.POST_DELETED).toBe('post_deleted')
    expect(enums.SuggestedPostState.PENDING).toBe('pending')
    expect(enums.TopChatCategory.USERS).toBe('users')
    expect(enums.UpgradedGiftOrigin.UPGRADE).toBe('upgrade')
    expect(enums.UserStatus.ONLINE).toBe('online')
    expect(enums.InlineButtonActionType.CALLBACK).toBe('callback')
  })
})
